### ISSUE TITLE
error when run with grails 2.4.4

### ISSUE THREAD

**Issue by dongwq** [kaleidos/grails-security-stateless#16]
| Error 2015-02-04 14:51:01,806 [localhost-startStop-1] ERROR [localhost].[/a]  - Exception starting filter springSecurityFilterChain
Message: No bean named 'springSecurityFilterChain' is defined
    Line | Method
->>  266 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
| Error 2015-02-04 14:51:01,856 [localhost-startStop-1] ERROR core.StandardContext  - Error filterStart
| Error 2015-02-04 14:51:01,857 [localhost-startStop-1] ERROR core.StandardContext  - Context [/a] startup failed due to previous errors

**Comment by Alotor** [comment]
Hi! Which version of Spring Security are you including?

**Comment by Alotor** [comment]
I close the issue if is still happening please don't hesitate to reopen the issue.

Thanks!
